version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/keacloud.dk:/etc/letsencrypt/live/keacloud.dk
      - /etc/letsencrypt/archive/keacloud.dk:/etc/letsencrypt/archive/keacloud.dk
    restart: always
