- name: Deploy Docker and run Hello World container
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Explicitly set Python 3 as the interpreter

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run hello-world container
      docker_container:
        name: hello-world
        image: hello-world
        state: started
        restart_policy: on-failure
- name: Deploy Docker and run Hello World container
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.7

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run hello-world container
      docker_container:
        name: hello-world
        image: hello-world
        state: started
        restart_policy: on-failure
