name: publish

on:
  push:
    branches: "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/full-pipeline:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key to runner
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/ssh_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          docker pull nginx
          docker run -d -p 80:80 --name hello-nginx nginx
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}